workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - validate
  - plan
  - apply
  - destroy

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init
    - terraform refresh
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .terraform/

terraform_validate:
  stage: validate
  script:
    - terraform validate

terraform_plan:
  stage: plan
  script:
    - terraform plan -var-file="terraform.tfvars" -out=tfplan
    - ls -la tfplan
  artifacts:
    name: "terraform-plan-$CI_COMMIT_REF_NAME"
    paths:
      - tfplan

terraform_apply:
  stage: apply
  dependencies:
    - terraform_plan
  script:
    - terraform apply --auto-approve tfplan
  when: manual
  allow_failure: false
  only:
    refs:
      - main

terraform_destroy:
  stage: destroy
  script:
    - terraform destroy -var-file="variables.tfvars" --auto-approve
  when: manual
  allow_failure: false
  only:
    refs:
      - main
